### PR TITLE
feat: implement Reconcile - ability to change upstream list on the fly

### PR DESCRIPTION
**Pull request by smira**
This is going to be used in Sfyra to provide dynamic load balancer for
the control plane.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]
Is it possible that adding any two routes can be done concurrently? If so, do we need a mutex?

**Comment by smira** [comment]
> Is it possible that adding any two routes can be done concurrently? If so, do we need a mutex?

good question, as `AddRoute` is not locked, I thought it's better to keep mutex-less for now (assuming single goroutine updates the routes and upstreams), but this can be changed of course.

**Comment by andrewrynhard** [comment]
> > Is it possible that adding any two routes can be done concurrently? If so, do we need a mutex?
> 
> good question, as `AddRoute` is not locked, I thought it's better to keep mutex-less for now (assuming single goroutine updates the routes and upstreams), but this can be changed of course.

SGTM

**Pull request merged**
